### ISSUE TITLE
Error bila nilai pixel > 3

### ISSUE THREAD

**Issue by LendisFabri** [LendisFabri/glcm-with-numpy#1]
Ketika salah satu nilai pixel saya ganti lebih dari 3. Akan muncul error berikut
![glcm-error](https://user-images.githubusercontent.com/16249870/43365567-01acdd48-9359-11e8-9ff5-0fac7d04742f.png)

Teks:
Traceback (most recent call last):
  File "glcm.py", line 10, in <module>
    result = greycomatrix(image, [1], [0, np.pi/2], levels=4, symmetric=True)
  File "/usr/lib/python2.7/dist-packages/skimage/feature/texture.py", line 87, in greycomatrix
    assert image.max() < levels
AssertionError

**Comment by ibnujakaria** [comment]
Itu error karena nilai maksimal piksel yang ada pada citra harus kurang dari parameter levels.

Kalau nilai maksimal piksel yg ada di citra misalnya 250, berarti levelnya harus 251 ke atas.

CMIIW

**Comment by ibnujakaria** [comment]
isu ini apakah belum close? @LendisFabri

**Comment by ibnujakaria** [comment]
up @LendisFabri
